### ISSUE TITLE
box-shadow 失效

### ISSUE THREAD

**Issue by lb091188** [jaywcjlove/AutoPrefixCSS#1]
styl

``` scss
.login-box
    position: absolute
    left: 50%
    top: 50%
    background: #fff
    width: 400px
    height: 300px
    margin-left: -(@width/2)
    margin-top: -(@height/2)
    padding: 30px
    opacity:0.5
    box-shadow:0 25px 25px 0 font-gray-light
```

根据以上的代码生成的css如下
css

``` css
.login-box {
    position: absolute;
    left: 50%;
    top: 50%;
    background: #fff;
    width: 400px;
    height: 300px;
    margin-left: -200px;
    margin-top: -150px;
    padding: 30px;
    -webkit-opacity: 0.5;
    -moz-opacity: 0.5;
    opacity: 0.5;
    filter: alpha(opacity=50);
    -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";
    box-shadow: 0 25px 25px 0 #999;
}
```

我用的是vue-cli webpack 脚手架，如上opacity是生效的，但是box-shadow是无效果的

**Comment by jaywcjlove** [comment]
@lb091188  经过测试应该没有问题。

我在测试用里面添加

``` css
div{
  box-shadow: 0 25px 25px 0 #999;
}
```

生成

``` css
div {
  -webkit-box-shadow: 0 25px 25px 0 #999;
  box-shadow: 0 25px 25px 0 #999;
}
```
